[project]
name = "dbt-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "js449", email = "jsingh284@yahoo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.4",
    "dbt-databricks>=1.10.9",
]

[project.scripts]
dbt-tutorial = "dbt_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
